name: Check pull request compliance

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  merge-checks:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup node, pnpm and install deps
        uses: ./.github/composites/setup-base-environment
      # Add Knip cache before other caching steps. This is the only way to cache knip results betwen CI runs, as turborepo cannot cache it.
      - name: Cache Knip Cache
        uses: actions/cache@v5
        with:
          path: ./node_modules/.cache/knip
          key: ${{ runner.os }}-knip-cache-${{ hashFiles('**/pnpm-lock.yaml', 'knip.jsonc') }}
          restore-keys: |
            ${{ runner.os }}-knip-cache-
      - name: Run qa checks
        run: pnpm qa
